controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
product_detail:
    path: '/product/{id}'
    controller: App\Controller\ProductController::detail
    # registration:
    # path: /register
    # controller: App\Controller\RegistrationController::register
